### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by sanjaysinghrajawat** [muziekklas/ScreenLocker#1]
How to run your application. I cannot understand properly.
If I run Screentroll.exe it open smile message show than automatically lock laptop.
What should I do ?

**Comment by sanjaysinghrajawat** [comment]
Please reply as soon as possible

**Comment by anton-kirschhock** [comment]
As soon as you run the app, it opens transparant windows on every screen. As soon as someone clicks or does something with the keyboard it takes a picture using the webcam and locks the PC after a second or two.

To abort use CTRL ALT F9, If I remember correctly.

Feel free to clone and inspect the code for more information  :)
